export {
  api,
  apiGet,
  apiPost,
  apiPut,
  apiPatch,
  apiDelete,
  API_URL,
  ApiRoutes,
  ApiError,
  getErrorMessage,
} from './client';

export {
  requireId,
  toNumberId,
  unwrapList,
  unwrapData,
} from './normalize';

export {
  authApi,
  projectsApi,
  tasksApi,
  logsApi,
  eventsApi,
  usersApi,
  notificationsApi,
  chatsApi,
} from './endpoints';

export { mapLogsToUi } from './mappers/logs';

export type { ApiRequestOptions, Id, HttpMethod, ApiErrorBody } from './types';
export type {
  User,
  Role,
  UpdateUserPayload,
  CreateTeamMemberPayload,
  SendOtpRequest,
  VerifyOtpRequest,
  AuthTokensResponse,
  RefreshTokenRequest,
  RegisterCompanyPayload,
  SendInvitationPayload,
  AuthSessionResponse,
  Project,
  CreateProjectPayload,
  UpdateProjectPayload,
  AssignProjectPayload,
  ProjectsListResponse,
  Task,
  TaskPriority,
  CreateTaskPayload,
  UpdateTaskPayload,
  AssignTaskPayload,
  FilterTasksPayload,
  TasksListResponse,
  LogEntry,
  LogImage,
  CreateLogPayload,
  UpdateLogPayload,
  LogsListResponse,
  AppEvent,
  CreateEventPayload,
  UpdateEventPayload,
  EventsListResponse,
  ExpoTokenRecord,
  SaveExpoTokenPayload,
  UserNotification,
  NotificationsListResponse,
  Conversation,
  ChatMessage,
  SendMessagePayload,
  CreateSignaturePayload,
  SubmitSignatureFile,
} from './models';
