export const ApiRoutes = {
  auth: {
    health: '/auth/health',
    register: '/auth/register',
    sendOtp: '/auth/otp/send',
    verifyOtp: '/auth/otp/verify',
    refreshToken: '/auth/token/refresh',
    session: '/auth/session',
    sendInvitation: '/auth/send-invitation',
  },
  users: {
    list: '/users',
    byId: (id) => `/users/${id}`,
    create: '/users',
    team: '/users/team',
    push: '/users/push-notifications',
    employeesForConversation: '/user/employees-for-conversation',
  },
  companies: {
    list: '/companies',
    create: '/companies',
    byId: (id) => `/companies/${id}`,
  },
  projects: {
    list: '/projects',
    forLogs: '/projects/for-logs',
    byId: (id) => `/projects/${id}`,
    assignedTasks: (id) => `/projects/${id}/assigned-tasks`,
    create: '/projects',
    assignToEmployees: '/project/assign-to-employees',
    employeesAssigned: (id) => `/project/employeesassigned/${id}`,
    files: (id) => `/project-files/${id}`,
  },
  tasks: {
    list: '/tasks',
    today: '/tasks/today',
    assignees: '/tasks/assignees',
    byId: (id) => `/tasks/${id}`,
    byProject: (projectId) => `/tasks/by-project/${projectId}`,
    byProjectWithLogs: (projectId) =>
      `/tasks/by-project/${projectId}/with-logs`,
    filter: '/tasks/filter',
    create: '/tasks',
    assign: (id) => `/tasks/${id}/assign`,
  },
  logs: {
    byProject: (projectId) => `/logs/by-project/${projectId}`,
    recentByProject: (projectId) => `/logs/by-project/${projectId}/recent`,
    byId: (id) => `/logs/${id}`,
    create: '/logs',
  },
  events: {
    list: '/events',
    upcoming: '/events/upcoming',
    byDate: (date) => `/events/by-date/${date}`,
    byId: (id) => `/events/${id}`,
    create: '/events',
  },
  images: {
    create: '/images',
    byId: (id) => `/images/${id}`,
  },
  notifications: {
    tokens: '/notifications/tokens',
    tokenById: (id) => `/notifications/tokens/${id}`,
    test: '/notifications/test',
  },
  userNotifications: {
    list: '/users-notifications/user',
    unread: '/users-notifications/unread',
    readAll: '/users-notifications/read-all',
    byId: (id) => `/users-notifications/${id}`,
    message: '/users-notifications/message',
    task: '/users-notifications',
    project: '/users-notifications/project',
    event: '/users-notifications/event',
  },
  chat: {
    conversations: '/chat/conversations',
    conversationMessages: (id, page, limit) =>
      `/chat/conversations/${id}/messages?page=${page}&limit=${limit}`,
    conversationFiles: (id) => `/chat/conversations/${id}/files`,
    messagesNew: '/chat/conversations/messages/new',
    messages: '/chat/messages',
    typing: '/chat/typing',
    projectConversation: (projectId) =>
      `/chat/project-conversations/${projectId}`,
  },
  signature: {
    messageWithSignature: '/signature/message-with-signature',
    byConversation: (conversationId) =>
      `/signature/signature/${conversationId}`,
    signedUser: '/signature/signed/user',
    uploadFile: (contractId) => `/signature/${contractId}/upload-file`,
  },
};
